# Generated by Django 4.2.5 on 2023-09-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=100)),
                ('ddd', models.CharField(max_length=2)),
            ],
        ),
    ]
