# Generated by Django 4.2.5 on 2023-09-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valida_cep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecos',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='ddd',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='enderecos',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
