# Generated by Django 4.2.5 on 2023-09-20 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valida_cep', '0002_alter_enderecos_bairro_alter_enderecos_cidade_and_more'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='valida_cep.enderecos'),
        ),
    ]
